<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Audit Trail Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 15px;
            border-bottom: 3px solid #333;
            padding-bottom: 15px;
        }
        .header h2 {
            margin: 0;
            color: #333;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .filter-summary {
            background: #f5f5f5;
            padding: 15px;
            margin-bottom: 10px;
            border-left: 4px solid #007bff;
        }
        .filter-summary h3 {
            margin-top: 0;
            color: #007bff;
        }
        .filter-summary p {
            margin: 2px 0;
        }
        .statistics {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        .stat-box {
            display: table-cell;
            width: 25%;
            padding: 15px;
            text-align: center;
            background: #e9ecef;
            border: 1px solid #dee2e6;
        }
        .stat-box h4 {
            margin: 0;
            color: #007bff;
            font-size: 24px;
        }
        .stat-box p {
            margin: 5px 0 0 0;
            color: #666;
            font-size: 11px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background: #007bff;
            color: white;
            padding: 8px;
            text-align: left;
            font-weight: bold;
            font-size: 11px;
        }
        td {
            padding: 6px 8px;
            border-bottom: 1px solid #ddd;
            font-size: 10px;
        }
        tr:nth-child(even) {
            background: #f9f9f9;
        }
        .badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 9px;
            font-weight: bold;
        }
        .badge-success { background: #28a745; color: white; }
        .badge-info { background: #17a2b8; color: white; }
        .badge-danger { background: #dc3545; color: white; }
        .badge-primary { background: #007bff; color: white; }
        .badge-secondary { background: #6c757d; color: white; }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #666;
            padding-top: 10px;
            border-top: 1px solid #ddd;
        }
        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h2>Audit Trail Report</h2>
        <p>Generated: {{ $generated_at }}</p>
        <p>Generated By: {{ $generated_by }}</p>
    </div>

    <!-- Filter Summary -->
    <div class="filter-summary">
        <h3>Report Criteria</h3>
        @foreach($filterSummary as $key => $value)
            <p><strong>{{ ucwords(str_replace('_', ' ', $key)) }}:</strong> {{ $value }}</p>
        @endforeach
    </div>

    <!-- Statistics -->
    <div class="statistics">
        <div class="stat-box">
            <h4>{{ $statistics['total_records'] }}</h4>
            <p>Total Records</p>
        </div>
        <div class="stat-box">
            <h4>{{ $statistics['actions_breakdown']->count() }}</h4>
            <p>Action Types</p>
        </div>
        <div class="stat-box">
            <h4>{{ $statistics['tables_affected']->count() }}</h4>
            <p>Tables Affected</p>
        </div>
        <div class="stat-box">
            <h4>{{ $audits->unique('user_id')->count() }}</h4>
            <p>Unique Users</p>
        </div>
    </div>

    <!-- Actions Breakdown -->
    <h3>Actions Breakdown</h3>
    <table>
        <thead>
            <tr>
                <th>Action</th>
                <th>Count</th>
                <th>Percentage</th>
            </tr>
        </thead>
        <tbody>
            @foreach($statistics['actions_breakdown'] as $action => $count)
            <tr>
                <td>
                    @php
                        $badgeClass = [
                            'INSERT' => 'badge-success',
                            'UPDATE' => 'badge-info',
                            'DELETE' => 'badge-danger',
                            'LOGIN' => 'badge-primary',
                            'LOGOUT' => 'badge-secondary'
                        ][$action] ?? 'badge-secondary';
                    @endphp
                    <span class="badge {{ $badgeClass }}">{{ $action }}</span>
                </td>
                <td>{{ $count }}</td>
                <td>{{ round(($count / $statistics['total_records']) * 100, 2) }}%</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="page-break"></div>

    <!-- Detailed Records -->
    <h3>Detailed Audit Records</h3>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Date & Time</th>
                <th>User</th>
                <th>Action</th>
                <th>Table</th>
                <th>Record ID</th>
                <th>Affected User</th>
                <th>IP Address</th>
            </tr>
        </thead>
        <tbody>
            @foreach($audits as $audit)
            <tr>
                <td>{{ $audit->id }}</td>
                <td>{{ $audit->created_at }}</td>
                <td>{{ $audit->user_name ?? 'Unknown' }}</td>
                <td>
                    @php
                        $badgeClass = [
                            'INSERT' => 'badge-success',
                            'UPDATE' => 'badge-info',
                            'DELETE' => 'badge-danger',
                            'LOGIN' => 'badge-primary',
                            'LOGOUT' => 'badge-secondary'
                        ][$audit->action] ?? 'badge-secondary';
                    @endphp
                    <span class="badge {{ $badgeClass }}">{{ $audit->action }}</span>
                </td>
                <td>{{ $audit->table_name }}</td>
                <td>{{ $audit->record_id }}</td>
                <td>{{ !empty(trim($audit->affected_user_name)) ? $audit->affected_user_name : 'N/A' }}</td>
                <td>{{ $audit->ip_address }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <!-- Footer -->
    <div class="footer">
        <p>This is a system-generated report. Page <span class="pagenum"></span></p>
        <p>Confidential - For authorized use only</p>
    </div>
</body>
</html>